title: Guobin Zhao's Homepage
page-top-title: 墨染不想回首
top-section-bg-text: Chemistry
home-subtitle: Guobin Zhao&ensp;|&ensp;赵国斌&ensp;|&ensp;자오구오빈
copyright-text: '&copy; ZHAOGUOBIN 2024. All Rights Reserved.'
